### ISSUE TITLE
git 底層原理

### ISSUE THREAD

**Issue by azole** [yihsiuchiu-nccu/git-practice#1]
那 git 是怎麼做到可以幫我們儲存不同版本的？diff 又是怎麼做到的？

> 希望可以趁這堂課的機會，更深入、全面的了解一些雲端服務，例如git不要只會pull, commit, push、docker只會拉ubunutu image當實驗節點。多跟老師、組員還有同學討論，從不同觀點、論述方式全面理解這些技術。

這是你在 video.md 中寫到的，為了協助你做到這件事，那我們來練習對事物有更多的「好奇心」，不要只停留在老師的問題上、也不要只停留在問題的表層上，你試試看把這些問題當作「起點」，而不是你的終點。

例如:
- git 是怎麼做到可以幫我們儲存不同版本的？
- diff 又是怎麼做到的？
- head 跟 branch 的關係是什麼？
- 每次一個檔案被編輯修改後，整個 `git add`, `git commit` 發生什麼事？
- ....

然後，也不要針對上面我舉例的問題逐一回答，這些問題只是舉例，試著自己去問更多的問題，然後真的全盤性地了解 git 是什麼。我看你的系級是博一，我想未來你做研究的路上，會很需要這樣的能力，趁現在、趁這門課，多練習，好嗎？期待你的新版本。

**Comment by azole** [comment]
如果有調整，要用 issue 回覆你調整的情況、想法等等喔。

**Comment by yihsiuchiu-nccu** [comment]
ok 謝謝老師 早上有根據老師的提問進行發想與紀錄(主要是版本檔案儲存的相關議題)

**Comment by azole** [comment]
舉手發問，你提到
> 尤其是當處理合併的時候，應該更能看出快照跟差異的差別

這邊可以詳細說明一下，到底什麼差異嗎？

**Comment by yihsiuchiu-nccu** [comment]
這裡的差異指的是"速度"差異。
因為合併的時候需要將多個版本(當初分支的版本、當前版本、合併目標版本)進行衝突比對，若使用差異的話，需要組合很多份版本的檔案再進行衝突比對；而在快照情境下，依hash值快速找到更改內容後就可以直接進行衝突比對。

**Comment by azole** [comment]
謝謝你的回覆，week 2 的課堂上對作業標準有更多的討論，繼續加油，期待你之後的作業。

如果沒有其他要跟我討論的部分，這個 issue 可以先 close 了。

**Comment by yihsiuchiu-nccu** [comment]
謝謝小賴老師！
